<a href="https://colab.research.google.com/github/Numan552/Deep-Learning/blob/main/RNN(simple_project).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/qna_dataset_605.csv")
df

,Question,Answer
0,Hi,Hello
1,Hello,Hi there
2,Good morning,Good morning
3,Good night,Good night
4,How are you,I am doing well
...,...,...
600,What is networking concept 146?,Networking concept 146 is related to computer ...
601,What is networking concept 147?,Networking concept 147 is related to computer ...
602,What is networking concept 148?,Networking concept 148 is related to computer ...
603,What is networking concept 149?,Networking concept 149 is related to computer ...
604,What is networking concept 150?,Networking concept 150 is related to computer ...

In [ ]:
df['Question']

0                                   Hi
1                                Hello
2                         Good morning
3                           Good night
4                          How are you
                    ...
600    What is networking concept 146?
601    What is networking concept 147?
602    What is networking concept 148?
603    What is networking concept 149?
604    What is networking concept 150?
Name: Question, Length: 605, dtype: object

Tokenization

In [ ]:
import re

def tokenize(text):
    text = text.lower()                      # lowercase
    text = re.sub(r"[\"']", "", text)        # remove quotes
    text = re.sub(r"[^a-z0-9\s]", " ", text) # remove punctuation
    text = re.sub(r"\s+", " ", text).strip() # replace multiple spaces with one

    tokens = text.split()                    # tokenize into words
    return tokens

In [ ]:
print (tokenize(df['Question'][5]))

['what', 'is', 'python', 'topic', '1']

Vocab Forming

In [ ]:
vocab = {'<UNK>':0}

In [ ]:
def build_voceb (row):

  #print(row['Question'], row['Answer'])

  tokenized_question = tokenize(row['Question'])
  tokenized_answer = tokenize(row['Answer'])

  merged_tokens = tokenized_question + tokenized_answer

  # print (merged_tokens)

  for token in merged_tokens:
    if token not in vocab:
      vocab[token]=len(vocab)

In [ ]:
df.apply(build_voceb, axis =1)

0      None
1      None
2      None
3      None
4      None
       ...
600    None
601    None
602    None
603    None
604    None
Length: 605, dtype: object

In [ ]:
vocab

{'<UNK>': 0,
 'hi': 1,
 'hello': 2,
 'there': 3,
 'good': 4,
 'morning': 5,
 'night': 6,
 'how': 7,
 'are': 8,
 'you': 9,
 'i': 10,
 'am': 11,
 'doing': 12,
 'well': 13,
 'what': 14,
 'is': 15,
 'python': 16,
 'topic': 17,
 '1': 18,
 'a': 19,
 'programming': 20,
 'concept': 21,
 '2': 22,
 '3': 23,
 '4': 24,
 '5': 25,
 '6': 26,
 '7': 27,
 '8': 28,
 '9': 29,
 '10': 30,
 '11': 31,
 '12': 32,
 '13': 33,
 '14': 34,
 '15': 35,
 '16': 36,
 '17': 37,
 '18': 38,
 '19': 39,
 '20': 40,
 '21': 41,
 '22': 42,
 '23': 43,
 '24': 44,
 '25': 45,
 '26': 46,
 '27': 47,
 '28': 48,
 '29': 49,
 '30': 50,
 '31': 51,
 '32': 52,
 '33': 53,
 '34': 54,
 '35': 55,
 '36': 56,
 '37': 57,
 '38': 58,
 '39': 59,
 '40': 60,
 '41': 61,
 '42': 62,
 '43': 63,
 '44': 64,
 '45': 65,
 '46': 66,
 '47': 67,
 '48': 68,
 '49': 69,
 '50': 70,
 '51': 71,
 '52': 72,
 '53': 73,
 '54': 74,
 '55': 75,
 '56': 76,
 '57': 77,
 '58': 78,
 '59': 79,
 '60': 80,
 '61': 81,
 '62': 82,
 '63': 83,
 '64': 84,
 '65': 85,
 '66': 86,
 '67': 87,
 '68': 88,
 '69': 89,
 '70': 90,
 '71': 91,
 '72': 92,
 '73': 93,
 '74': 94,
 '75': 95,
 '76': 96,
 '77': 97,
 '78': 98,
 '79': 99,
 '80': 100,
 '81': 101,
 '82': 102,
 '83': 103,
 '84': 104,
 '85': 105,
 '86': 106,
 '87': 107,
 '88': 108,
 '89': 109,
 '90': 110,
 '91': 111,
 '92': 112,
 '93': 113,
 '94': 114,
 '95': 115,
 '96': 116,
 '97': 117,
 '98': 118,
 '99': 119,
 '100': 120,
 '101': 121,
 '102': 122,
 '103': 123,
 '104': 124,
 '105': 125,
 '106': 126,
 '107': 127,
 '108': 128,
 '109': 129,
 '110': 130,
 '111': 131,
 '112': 132,
 '113': 133,
 '114': 134,
 '115': 135,
 '116': 136,
 '117': 137,
 '118': 138,
 '119': 139,
 '120': 140,
 '121': 141,
 '122': 142,
 '123': 143,
 '124': 144,
 '125': 145,
 '126': 146,
 '127': 147,
 '128': 148,
 '129': 149,
 '130': 150,
 '131': 151,
 '132': 152,
 '133': 153,
 '134': 154,
 '135': 155,
 '136': 156,
 '137': 157,
 '138': 158,
 '139': 159,
 '140': 160,
 '141': 161,
 '142': 162,
 '143': 163,
 '144': 164,
 '145': 165,
 '146': 166,
 '147': 167,
 '148': 168,
 '149': 169,
 '150': 170,
 'machine': 171,
 'learning': 172,
 'helps': 173,
 'computers': 174,
 'learn': 175,
 'from': 176,
 'data': 177,
 'database': 178,
 'related': 179,
 'to': 180,
 'storage': 181,
 'and': 182,
 'management': 183,
 'networking': 184,
 'computer': 185,
 'communication': 186}

# Text to Indices

In [ ]:
def text_to_indices(text,vocab):
  indexed_text = []

  for token in tokenize(text):
    if token in vocab:
      # print(vocab[token])
      indexed_text.append(vocab[token])

    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [ ]:
text_to_indices("What is Phitron", vocab)

[14, 15, 0]

# Dataset and Data loader

In [ ]:
import torch
from torch.utils.data import Dataset,DataLoader

In [ ]:
df.shape[0]

605

In [ ]:
index =0
text_to_indices(df.iloc[index]['Question'],vocab)

[1]

In [ ]:
class QADataset(Dataset):

  def __init__(self , df,vocab):
    self.df =df
    self.vocab =vocab
  def __len__(self):
    return self.df.shape[0]
  def __getitem__(self,index):
    numerical_question = text_to_indices (self.df.iloc[index]['Question'],self.vocab)
    numerical_answer = text_to_indices (self.df.iloc[index]['Answer'],self.vocab)

    return torch.tensor(numerical_question), torch.tensor(numerical_answer)

In [ ]:
dataset = QADataset(df, vocab)

In [ ]:
dataset[1]

(tensor([2]), tensor([1, 3]))

In [ ]:
dataloader = DataLoader(dataset , batch_size=1 , shuffle=True)

In [ ]:
for Question, Answer in dataloader:
  print(Question, Answer[0])

tensor([[ 14,  15,  16,  17, 143]]) tensor([ 16,  17, 143,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21, 166]]) tensor([184,  21, 166,  15, 179, 180, 185, 186])
tensor([[14, 15, 16, 17, 65]]) tensor([16, 17, 65, 15, 19, 20, 21])
tensor([[ 14,  15, 178,  21, 147]]) tensor([178,  21, 147,  15, 179, 180, 177, 181, 182, 183])
tensor([[14, 15, 16, 17, 74]]) tensor([16, 17, 74, 15, 19, 20, 21])
tensor([[ 14,  15, 171, 172,  21,  29]]) tensor([171, 172,  21,  29, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 178,  21, 141]]) tensor([178,  21, 141,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21,  18]]) tensor([178,  21,  18,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21, 109]]) tensor([171, 172,  21, 109, 173, 174, 175, 176, 177])
tensor([[ 14,  15,  16,  17, 168]]) tensor([ 16,  17, 168,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21,  78]]) tensor([184,  21,  78,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21, 113]]) tensor([178,  21, 113,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21,  70]]) tensor([178,  21,  70,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21,  80]]) tensor([171, 172,  21,  80, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 178,  21, 134]]) tensor([178,  21, 134,  15, 179, 180, 177, 181, 182, 183])
tensor([[14, 15, 16, 17, 90]]) tensor([16, 17, 90, 15, 19, 20, 21])
tensor([[ 14,  15, 171, 172,  21, 153]]) tensor([171, 172,  21, 153, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21,  25]]) tensor([184,  21,  25,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21,  25]]) tensor([178,  21,  25,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21, 108]]) tensor([178,  21, 108,  15, 179, 180, 177, 181, 182, 183])
tensor([[14, 15, 16, 17, 73]]) tensor([16, 17, 73, 15, 19, 20, 21])
tensor([[14, 15, 16, 17, 57]]) tensor([16, 17, 57, 15, 19, 20, 21])
tensor([[4, 5]]) tensor([4, 5])
tensor([[ 14,  15,  16,  17, 107]]) tensor([ 16,  17, 107,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21, 156]]) tensor([184,  21, 156,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21,  96]]) tensor([171, 172,  21,  96, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21,  88]]) tensor([171, 172,  21,  88, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21, 144]]) tensor([171, 172,  21, 144, 173, 174, 175, 176, 177])
tensor([[14, 15, 16, 17, 64]]) tensor([16, 17, 64, 15, 19, 20, 21])
tensor([[ 14,  15,  16,  17, 105]]) tensor([ 16,  17, 105,  15,  19,  20,  21])
tensor([[ 14,  15, 178,  21,  65]]) tensor([178,  21,  65,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21,  38]]) tensor([171, 172,  21,  38, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21, 128]]) tensor([184,  21, 128,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 184,  21, 168]]) tensor([184,  21, 168,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21, 148]]) tensor([178,  21, 148,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 184,  21,  79]]) tensor([184,  21,  79,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21, 139]]) tensor([178,  21, 139,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21,  23]]) tensor([178,  21,  23,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21, 160]]) tensor([178,  21, 160,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15,  16,  17, 111]]) tensor([ 16,  17, 111,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21, 150]]) tensor([184,  21, 150,  15, 179, 180, 185, 186])
tensor([[14, 15, 16, 17, 67]]) tensor([16, 17, 67, 15, 19, 20, 21])
tensor([[ 14,  15,  16,  17, 153]]) tensor([ 16,  17, 153,  15,  19,  20,  21])
tensor([[14, 15, 16, 17, 95]]) tensor([16, 17, 95, 15, 19, 20, 21])
tensor([[ 14,  15, 171, 172,  21,  61]]) tensor([171, 172,  21,  61, 173, 174, 175, 176, 177])
tensor([[14, 15, 16, 17, 45]]) tensor([16, 17, 45, 15, 19, 20, 21])
tensor([[ 14,  15, 178,  21,  97]]) tensor([178,  21,  97,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21, 161]]) tensor([171, 172,  21, 161, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21, 103]]) tensor([184,  21, 103,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21,  37]]) tensor([171, 172,  21,  37, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21, 149]]) tensor([171, 172,  21, 149, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21, 112]]) tensor([171, 172,  21, 112, 173, 174, 175, 176, 177])
tensor([[ 14,  15,  16,  17, 120]]) tensor([ 16,  17, 120,  15,  19,  20,  21])
tensor([[ 14,  15, 178,  21,  67]]) tensor([178,  21,  67,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21, 155]]) tensor([171, 172,  21, 155, 173, 174, 175, 176, 177])
tensor([[14, 15, 16, 17, 25]]) tensor([16, 17, 25, 15, 19, 20, 21])
tensor([[ 14,  15, 184,  21,  23]]) tensor([184,  21,  23,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21,  77]]) tensor([178,  21,  77,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21,  80]]) tensor([178,  21,  80,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 184,  21, 163]]) tensor([184,  21, 163,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21, 154]]) tensor([178,  21, 154,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21,  82]]) tensor([178,  21,  82,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21,  56]]) tensor([171, 172,  21,  56, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21,  80]]) tensor([184,  21,  80,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21, 130]]) tensor([171, 172,  21, 130, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21,  84]]) tensor([184,  21,  84,  15, 179, 180, 185, 186])
tensor([[ 14,  15,  16,  17, 119]]) tensor([ 16,  17, 119,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21,  30]]) tensor([184,  21,  30,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21, 145]]) tensor([178,  21, 145,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15,  16,  17, 138]]) tensor([ 16,  17, 138,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21,  69]]) tensor([184,  21,  69,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21,  49]]) tensor([178,  21,  49,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21,  28]]) tensor([171, 172,  21,  28, 173, 174, 175, 176, 177])
tensor([[14, 15, 16, 17, 46]]) tensor([16, 17, 46, 15, 19, 20, 21])
tensor([[ 14,  15,  16,  17, 122]]) tensor([ 16,  17, 122,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21, 110]]) tensor([184,  21, 110,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21, 111]]) tensor([171, 172,  21, 111, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21, 131]]) tensor([184,  21, 131,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21, 107]]) tensor([171, 172,  21, 107, 173, 174, 175, 176, 177])
tensor([[ 14,  15,  16,  17, 147]]) tensor([ 16,  17, 147,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21, 115]]) tensor([184,  21, 115,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21,  36]]) tensor([171, 172,  21,  36, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21, 169]]) tensor([184,  21, 169,  15, 179, 180, 185, 186])
tensor([[2]]) tensor([1, 3])
tensor([[ 14,  15, 171, 172,  21,  51]]) tensor([171, 172,  21,  51, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21,  36]]) tensor([184,  21,  36,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 184,  21,  91]]) tensor([184,  21,  91,  15, 179, 180, 185, 186])
tensor([[14, 15, 16, 17, 35]]) tensor([16, 17, 35, 15, 19, 20, 21])
tensor([[ 14,  15, 171, 172,  21, 104]]) tensor([171, 172,  21, 104, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21, 163]]) tensor([171, 172,  21, 163, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21, 102]]) tensor([184,  21, 102,  15, 179, 180, 185, 186])
tensor([[ 14,  15,  16,  17, 110]]) tensor([ 16,  17, 110,  15,  19,  20,  21])
tensor([[ 14,  15, 171, 172,  21,  95]]) tensor([171, 172,  21,  95, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21, 115]]) tensor([171, 172,  21, 115, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 178,  21, 169]]) tensor([178,  21, 169,  15, 179, 180, 177, 181, 182, 183])
tensor([[14, 15, 16, 17, 89]]) tensor([16, 17, 89, 15, 19, 20, 21])
tensor([[ 14,  15, 171, 172,  21,  18]]) tensor([171, 172,  21,  18, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21,  70]]) tensor([184,  21,  70,  15, 179, 180, 185, 186])
tensor([[14, 15, 16, 17, 36]]) tensor([16, 17, 36, 15, 19, 20, 21])
tensor([[ 14,  15, 178,  21,  95]]) tensor([178,  21,  95,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21,  74]]) tensor([178,  21,  74,  15, 179, 180, 177, 181, 182, 183])
tensor([[14, 15, 16, 17, 56]]) tensor([16, 17, 56, 15, 19, 20, 21])
tensor([[ 14,  15, 171, 172,  21,  35]]) tensor([171, 172,  21,  35, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21, 145]]) tensor([171, 172,  21, 145, 173, 174, 175, 176, 177])
tensor([[ 14,  15,  16,  17, 146]]) tensor([ 16,  17, 146,  15,  19,  20,  21])
tensor([[ 14,  15,  16,  17, 114]]) tensor([ 16,  17, 114,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21,  57]]) tensor([184,  21,  57,  15, 179, 180, 185, 186])
tensor([[ 14,  15,  16,  17, 161]]) tensor([ 16,  17, 161,  15,  19,  20,  21])
tensor([[ 14,  15, 178,  21,  78]]) tensor([178,  21,  78,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21, 101]]) tensor([171, 172,  21, 101, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21,  22]]) tensor([171, 172,  21,  22, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21,  48]]) tensor([171, 172,  21,  48, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21,  34]]) tensor([184,  21,  34,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21, 133]]) tensor([178,  21, 133,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21,  31]]) tensor([178,  21,  31,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21, 110]]) tensor([171, 172,  21, 110, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21, 152]]) tensor([184,  21, 152,  15, 179, 180, 185, 186])
tensor([[14, 15, 16, 17, 32]]) tensor([16, 17, 32, 15, 19, 20, 21])
tensor([[14, 15, 16, 17, 99]]) tensor([16, 17, 99, 15, 19, 20, 21])
tensor([[ 14,  15, 184,  21,  67]]) tensor([184,  21,  67,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 184,  21,  55]]) tensor([184,  21,  55,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21,  72]]) tensor([171, 172,  21,  72, 173, 174, 175, 176, 177])
tensor([[ 14,  15,  16,  17, 115]]) tensor([ 16,  17, 115,  15,  19,  20,  21])
tensor([[ 14,  15, 171, 172,  21,  97]]) tensor([171, 172,  21,  97, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21,  46]]) tensor([171, 172,  21,  46, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 178,  21,  26]]) tensor([178,  21,  26,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21,  44]]) tensor([178,  21,  44,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21,  39]]) tensor([171, 172,  21,  39, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21,  94]]) tensor([184,  21,  94,  15, 179, 180, 185, 186])
tensor([[ 14,  15,  16,  17, 164]]) tensor([ 16,  17, 164,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21, 143]]) tensor([184,  21, 143,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21,  73]]) tensor([178,  21,  73,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21, 146]]) tensor([178,  21, 146,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15,  16,  17, 142]]) tensor([ 16,  17, 142,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21, 121]]) tensor([184,  21, 121,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21,  71]]) tensor([178,  21,  71,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21, 157]]) tensor([178,  21, 157,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21,  27]]) tensor([178,  21,  27,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 184,  21,  37]]) tensor([184,  21,  37,  15, 179, 180, 185, 186])
tensor([[14, 15, 16, 17, 53]]) tensor([16, 17, 53, 15, 19, 20, 21])
tensor([[ 14,  15, 171, 172,  21,  79]]) tensor([171, 172,  21,  79, 173, 174, 175, 176, 177])
tensor([[14, 15, 16, 17, 76]]) tensor([16, 17, 76, 15, 19, 20, 21])
tensor([[ 14,  15, 178,  21, 119]]) tensor([178,  21, 119,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 184,  21, 108]]) tensor([184,  21, 108,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21,  59]]) tensor([171, 172,  21,  59, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21, 159]]) tensor([171, 172,  21, 159, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 178,  21, 144]]) tensor([178,  21, 144,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21, 102]]) tensor([171, 172,  21, 102, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21, 142]]) tensor([184,  21, 142,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21,  94]]) tensor([178,  21,  94,  15, 179, 180, 177, 181, 182, 183])
tensor([[14, 15, 16, 17, 27]]) tensor([16, 17, 27, 15, 19, 20, 21])
tensor([[ 14,  15, 171, 172,  21, 164]]) tensor([171, 172,  21, 164, 173, 174, 175, 176, 177])
tensor([[14, 15, 16, 17, 26]]) tensor([16, 17, 26, 15, 19, 20, 21])
tensor([[ 14,  15, 178,  21,  38]]) tensor([178,  21,  38,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21,  99]]) tensor([171, 172,  21,  99, 173, 174, 175, 176, 177])
tensor([[ 14,  15,  16,  17, 148]]) tensor([ 16,  17, 148,  15,  19,  20,  21])
tensor([[ 14,  15, 171, 172,  21,  78]]) tensor([171, 172,  21,  78, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 178,  21, 124]]) tensor([178,  21, 124,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21, 148]]) tensor([171, 172,  21, 148, 173, 174, 175, 176, 177])
tensor([[14, 15, 16, 17, 68]]) tensor([16, 17, 68, 15, 19, 20, 21])
tensor([[ 14,  15, 171, 172,  21,  50]]) tensor([171, 172,  21,  50, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21, 156]]) tensor([171, 172,  21, 156, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21,  25]]) tensor([171, 172,  21,  25, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21,  99]]) tensor([184,  21,  99,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21,  91]]) tensor([171, 172,  21,  91, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 178,  21, 166]]) tensor([178,  21, 166,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 184,  21, 135]]) tensor([184,  21, 135,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21,  62]]) tensor([171, 172,  21,  62, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21,  50]]) tensor([184,  21,  50,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21,  49]]) tensor([171, 172,  21,  49, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21,  49]]) tensor([184,  21,  49,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 184,  21,  95]]) tensor([184,  21,  95,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 184,  21,  42]]) tensor([184,  21,  42,  15, 179, 180, 185, 186])
tensor([[ 14,  15,  16,  17, 150]]) tensor([ 16,  17, 150,  15,  19,  20,  21])
tensor([[ 14,  15, 171, 172,  21, 123]]) tensor([171, 172,  21, 123, 173, 174, 175, 176, 177])
tensor([[ 14,  15,  16,  17, 156]]) tensor([ 16,  17, 156,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21,  73]]) tensor([184,  21,  73,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 184,  21,  43]]) tensor([184,  21,  43,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 184,  21,  86]]) tensor([184,  21,  86,  15, 179, 180, 185, 186])
tensor([[ 14,  15,  16,  17, 149]]) tensor([ 16,  17, 149,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21, 109]]) tensor([184,  21, 109,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 184,  21,  64]]) tensor([184,  21,  64,  15, 179, 180, 185, 186])
tensor([[14, 15, 16, 17, 59]]) tensor([16, 17, 59, 15, 19, 20, 21])
tensor([[ 14,  15, 178,  21,  37]]) tensor([178,  21,  37,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21, 143]]) tensor([178,  21, 143,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21,  94]]) tensor([171, 172,  21,  94, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21, 132]]) tensor([171, 172,  21, 132, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21, 118]]) tensor([184,  21, 118,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21, 127]]) tensor([171, 172,  21, 127, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 178,  21, 153]]) tensor([178,  21, 153,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21,  60]]) tensor([171, 172,  21,  60, 173, 174, 175, 176, 177])
tensor([[14, 15, 16, 17, 63]]) tensor([16, 17, 63, 15, 19, 20, 21])
tensor([[ 14,  15,  16,  17, 158]]) tensor([ 16,  17, 158,  15,  19,  20,  21])
tensor([[ 14,  15,  16,  17, 128]]) tensor([ 16,  17, 128,  15,  19,  20,  21])
tensor([[14, 15, 16, 17, 98]]) tensor([16, 17, 98, 15, 19, 20, 21])
tensor([[ 14,  15, 171, 172,  21,  86]]) tensor([171, 172,  21,  86, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21,  29]]) tensor([184,  21,  29,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21, 160]]) tensor([171, 172,  21, 160, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21,  90]]) tensor([171, 172,  21,  90, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21, 103]]) tensor([171, 172,  21, 103, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21,  45]]) tensor([171, 172,  21,  45, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21, 150]]) tensor([171, 172,  21, 150, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 178,  21,  47]]) tensor([178,  21,  47,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21,  72]]) tensor([178,  21,  72,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 184,  21,  35]]) tensor([184,  21,  35,  15, 179, 180, 185, 186])
tensor([[14, 15, 16, 17, 23]]) tensor([16, 17, 23, 15, 19, 20, 21])
tensor([[ 14,  15, 178,  21,  85]]) tensor([178,  21,  85,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21,  22]]) tensor([178,  21,  22,  15, 179, 180, 177, 181, 182, 183])
tensor([[14, 15, 16, 17, 47]]) tensor([16, 17, 47, 15, 19, 20, 21])
tensor([[ 14,  15, 184,  21, 106]]) tensor([184,  21, 106,  15, 179, 180, 185, 186])
tensor([[14, 15, 16, 17, 41]]) tensor([16, 17, 41, 15, 19, 20, 21])
tensor([[7, 8, 9]]) tensor([10, 11, 12, 13])
tensor([[14, 15, 16, 17, 84]]) tensor([16, 17, 84, 15, 19, 20, 21])
tensor([[ 14,  15, 171, 172,  21,  30]]) tensor([171, 172,  21,  30, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21,  63]]) tensor([184,  21,  63,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21,  70]]) tensor([171, 172,  21,  70, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 171, 172,  21, 143]]) tensor([171, 172,  21, 143, 173, 174, 175, 176, 177])
tensor([[ 14,  15,  16,  17, 152]]) tensor([ 16,  17, 152,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21, 112]]) tensor([184,  21, 112,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21,  88]]) tensor([178,  21,  88,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15,  16,  17, 136]]) tensor([ 16,  17, 136,  15,  19,  20,  21])
tensor([[ 14,  15, 178,  21,  64]]) tensor([178,  21,  64,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15,  16,  17, 101]]) tensor([ 16,  17, 101,  15,  19,  20,  21])
tensor([[ 14,  15,  16,  17, 139]]) tensor([ 16,  17, 139,  15,  19,  20,  21])
tensor([[14, 15, 16, 17, 78]]) tensor([16, 17, 78, 15, 19, 20, 21])
tensor([[ 14,  15, 184,  21,  38]]) tensor([184,  21,  38,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21,  84]]) tensor([178,  21,  84,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21,  31]]) tensor([171, 172,  21,  31, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 184,  21,  66]]) tensor([184,  21,  66,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 171, 172,  21, 147]]) tensor([171, 172,  21, 147, 173, 174, 175, 176, 177])

squeeze

In [ ]:
import torch

x=torch.tensor([[[1,2,3]]])

print(x.shape)

y= x.squeeze(0)
print(y.shape)

torch.Size([1, 1, 3])
torch.Size([1, 3])

# RNN architecture implementation

In [ ]:
import torch.nn as nn

class simpleRNN(nn.Module):
  def __init__(self, vocab_size , embedding_dim =50 , hidden_size=64):
    super().__init__()

    self.embedding = nn.Embedding(vocab_size , embedding_dim)
    self.rnn = nn.RNN(embedding_dim , hidden_size, batch_first=True)
    self.fc = nn.Linear(hidden_size, vocab_size)

  def forward (self, Question):
    embedded = self.embedding(Question)
    _,final = self.rnn(embedded)

    return self.fc(final.squeeze(0))

In [ ]:
model = simpleRNN(vocab_size=len(vocab))

# Training loop

In [ ]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)
epochs =50

In [ ]:
for epoch in range(epochs):
  total_loss=0
  for Question,Answer in dataloader:
    optimizer.zero_grad()
    output = model(Question)

    target = Answer[0][0].unsqueeze(0)

    loss = criterion(output, target)
    loss.backward()
    optimizer.step()
    total_loss+=loss.item()

  if (epoch + 1) % 10 == 0:
    print(f"Epoch{epoch+1:3d}/{epochs}|Loss:{total_loss:.4f}")

Epoch 10/50|Loss:21.0342
Epoch 20/50|Loss:2.9516
Epoch 30/50|Loss:0.3785
Epoch 40/50|Loss:0.0653
Epoch 50/50|Loss:0.0135

# Prediction

In [ ]:
vocab.items()

dict_items([('<UNK>', 0), ('hi', 1), ('hello', 2), ('there', 3), ('good', 4), ('morning', 5), ('night', 6), ('how', 7), ('are', 8), ('you', 9), ('i', 10), ('am', 11), ('doing', 12), ('well', 13), ('what', 14), ('is', 15), ('python', 16), ('topic', 17), ('1', 18), ('a', 19), ('programming', 20), ('concept', 21), ('2', 22), ('3', 23), ('4', 24), ('5', 25), ('6', 26), ('7', 27), ('8', 28), ('9', 29), ('10', 30), ('11', 31), ('12', 32), ('13', 33), ('14', 34), ('15', 35), ('16', 36), ('17', 37), ('18', 38), ('19', 39), ('20', 40), ('21', 41), ('22', 42), ('23', 43), ('24', 44), ('25', 45), ('26', 46), ('27', 47), ('28', 48), ('29', 49), ('30', 50), ('31', 51), ('32', 52), ('33', 53), ('34', 54), ('35', 55), ('36', 56), ('37', 57), ('38', 58), ('39', 59), ('40', 60), ('41', 61), ('42', 62), ('43', 63), ('44', 64), ('45', 65), ('46', 66), ('47', 67), ('48', 68), ('49', 69), ('50', 70), ('51', 71), ('52', 72), ('53', 73), ('54', 74), ('55', 75), ('56', 76), ('57', 77), ('58', 78), ('59', 79), ('60', 80), ('61', 81), ('62', 82), ('63', 83), ('64', 84), ('65', 85), ('66', 86), ('67', 87), ('68', 88), ('69', 89), ('70', 90), ('71', 91), ('72', 92), ('73', 93), ('74', 94), ('75', 95), ('76', 96), ('77', 97), ('78', 98), ('79', 99), ('80', 100), ('81', 101), ('82', 102), ('83', 103), ('84', 104), ('85', 105), ('86', 106), ('87', 107), ('88', 108), ('89', 109), ('90', 110), ('91', 111), ('92', 112), ('93', 113), ('94', 114), ('95', 115), ('96', 116), ('97', 117), ('98', 118), ('99', 119), ('100', 120), ('101', 121), ('102', 122), ('103', 123), ('104', 124), ('105', 125), ('106', 126), ('107', 127), ('108', 128), ('109', 129), ('110', 130), ('111', 131), ('112', 132), ('113', 133), ('114', 134), ('115', 135), ('116', 136), ('117', 137), ('118', 138), ('119', 139), ('120', 140), ('121', 141), ('122', 142), ('123', 143), ('124', 144), ('125', 145), ('126', 146), ('127', 147), ('128', 148), ('129', 149), ('130', 150), ('131', 151), ('132', 152), ('133', 153), ('134', 154), ('135', 155), ('136', 156), ('137', 157), ('138', 158), ('139', 159), ('140', 160), ('141', 161), ('142', 162), ('143', 163), ('144', 164), ('145', 165), ('146', 166), ('147', 167), ('148', 168), ('149', 169), ('150', 170), ('machine', 171), ('learning', 172), ('helps', 173), ('computers', 174), ('learn', 175), ('from', 176), ('data', 177), ('database', 178), ('related', 179), ('to', 180), ('storage', 181), ('and', 182), ('management', 183), ('networking', 184), ('computer', 185), ('communication', 186)])

In [ ]:
idx_to_word = {idx:word for word, idx in vocab.items()}
idx_to_word

{0: '<UNK>',
 1: 'hi',
 2: 'hello',
 3: 'there',
 4: 'good',
 5: 'morning',
 6: 'night',
 7: 'how',
 8: 'are',
 9: 'you',
 10: 'i',
 11: 'am',
 12: 'doing',
 13: 'well',
 14: 'what',
 15: 'is',
 16: 'python',
 17: 'topic',
 18: '1',
 19: 'a',
 20: 'programming',
 21: 'concept',
 22: '2',
 23: '3',
 24: '4',
 25: '5',
 26: '6',
 27: '7',
 28: '8',
 29: '9',
 30: '10',
 31: '11',
 32: '12',
 33: '13',
 34: '14',
 35: '15',
 36: '16',
 37: '17',
 38: '18',
 39: '19',
 40: '20',
 41: '21',
 42: '22',
 43: '23',
 44: '24',
 45: '25',
 46: '26',
 47: '27',
 48: '28',
 49: '29',
 50: '30',
 51: '31',
 52: '32',
 53: '33',
 54: '34',
 55: '35',
 56: '36',
 57: '37',
 58: '38',
 59: '39',
 60: '40',
 61: '41',
 62: '42',
 63: '43',
 64: '44',
 65: '45',
 66: '46',
 67: '47',
 68: '48',
 69: '49',
 70: '50',
 71: '51',
 72: '52',
 73: '53',
 74: '54',
 75: '55',
 76: '56',
 77: '57',
 78: '58',
 79: '59',
 80: '60',
 81: '61',
 82: '62',
 83: '63',
 84: '64',
 85: '65',
 86: '66',
 87: '67',
 88: '68',
 89: '69',
 90: '70',
 91: '71',
 92: '72',
 93: '73',
 94: '74',
 95: '75',
 96: '76',
 97: '77',
 98: '78',
 99: '79',
 100: '80',
 101: '81',
 102: '82',
 103: '83',
 104: '84',
 105: '85',
 106: '86',
 107: '87',
 108: '88',
 109: '89',
 110: '90',
 111: '91',
 112: '92',
 113: '93',
 114: '94',
 115: '95',
 116: '96',
 117: '97',
 118: '98',
 119: '99',
 120: '100',
 121: '101',
 122: '102',
 123: '103',
 124: '104',
 125: '105',
 126: '106',
 127: '107',
 128: '108',
 129: '109',
 130: '110',
 131: '111',
 132: '112',
 133: '113',
 134: '114',
 135: '115',
 136: '116',
 137: '117',
 138: '118',
 139: '119',
 140: '120',
 141: '121',
 142: '122',
 143: '123',
 144: '124',
 145: '125',
 146: '126',
 147: '127',
 148: '128',
 149: '129',
 150: '130',
 151: '131',
 152: '132',
 153: '133',
 154: '134',
 155: '135',
 156: '136',
 157: '137',
 158: '138',
 159: '139',
 160: '140',
 161: '141',
 162: '142',
 163: '143',
 164: '144',
 165: '145',
 166: '146',
 167: '147',
 168: '148',
 169: '149',
 170: '150',
 171: 'machine',
 172: 'learning',
 173: 'helps',
 174: 'computers',
 175: 'learn',
 176: 'from',
 177: 'data',
 178: 'database',
 179: 'related',
 180: 'to',
 181: 'storage',
 182: 'and',
 183: 'management',
 184: 'networking',
 185: 'computer',
 186: 'communication'}

In [ ]:
def predict(question_text , model, vocab , idx_to_word):
  model.eval()

  with torch.no_grad():
    indices = text_to_indices( question_text , vocab)

    if not indices:
      return"<UNK>"

    x= torch.tensor(indices).unsqueeze(0)

    pred = torch.argmax(model(x),dim=1).item()

  return idx_to_word.get(pred,"<UNK>")

test

In [ ]:
tests =[
    "Hi",
    "Good morning",
    "How are you"

]

for q in tests:
  print(f"{q:45}={predict(q,model,vocab,idx_to_word)}")

Hi                                           =hello
Good morning                                 =good
How are you                                  =i